### ISSUE TITLE
Implementation of the Library doesn't works

### ISSUE THREAD

**Issue by the-rebooted-coder** [rich-it/MaterialOfficeAbout#1]
I just got amazed by this library but found that it is no longer getting installed in my android app from the `  implementation 'com.github.p32929:MaterialOfficeAbout:1.0.5'` line.

Could the developers please have a look at it!

**Comment by p32929** [comment]
What's the error?

**Comment by the-rebooted-coder** [comment]
When I am adding the implementation line the file is not getting downloaded properly I guess because the methods could not be implemented in the Java File

**Comment by p32929** [comment]
Thanks for the issue. Otherwise, I might have not known it.

Probably it was a problem with the hosting ( jitpack ). So, I updated the readme again. It will work now. Try with this:

`implementation 'com.github.p32929:MaterialOfficeAbout:1.0.6'`

**Comment by the-rebooted-coder** [comment]
Great Work Pal!
